
/**
 * @sveltech/routify 1.9.9
 * File generated Fri Oct 09 2020 21:48:46 GMT+0900 (Korean Standard Time)
 */

export const __version = "1.9.9"
export const __timestamp = "2020-10-09T12:48:46.439Z"

//buildRoutes
import { buildClientTree } from "@sveltech/routify/runtime/buildRoutes"

//imports


//options
export const options = {}

//tree
export const _tree = {
  "name": "root",
  "filepath": "/",
  "root": true,
  "ownMeta": {},
  "absolutePath": "src/pages",
  "children": [
    {
      "isFile": true,
      "isDir": false,
      "file": "_fallback.svelte",
      "filepath": "/_fallback.svelte",
      "name": "_fallback",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/_fallback.svelte",
      "importPath": "../src/pages/_fallback.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": true,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "preload": false,
        "prerender": true,
        "precache-order": false,
        "precache-proximity": true,
        "recursive": true
      },
      "path": "/_fallback",
      "id": "__fallback",
      "component": () => import('../src/pages/_fallback.svelte').then(m => m.default)
    },
    {
      "isFile": true,
      "isDir": false,
      "file": "_layout.svelte",
      "filepath": "/_layout.svelte",
      "name": "_layout",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/_layout.svelte",
      "importPath": "../src/pages/_layout.svelte",
      "isLayout": true,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "preload": false,
        "prerender": true,
        "precache-order": false,
        "precache-proximity": true,
        "recursive": true
      },
      "path": "/",
      "id": "__layout",
      "component": () => import('../src/pages/_layout.svelte').then(m => m.default)
    },
    {
      "isFile": false,
      "isDir": true,
      "file": "example",
      "filepath": "/example",
      "name": "example",
      "ext": "",
      "badExt": false,
      "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example",
      "children": [
        {
          "isFile": true,
          "isDir": false,
          "file": "_fallback.svelte",
          "filepath": "/example/_fallback.svelte",
          "name": "_fallback",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/_fallback.svelte",
          "importPath": "../src/pages/example/_fallback.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": true,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example/_fallback",
          "id": "_example__fallback",
          "component": () => import('../src/pages/example/_fallback.svelte').then(m => m.default)
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "_reset.svelte",
          "filepath": "/example/_reset.svelte",
          "name": "_reset",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/_reset.svelte",
          "importPath": "../src/pages/example/_reset.svelte",
          "isLayout": true,
          "isReset": true,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example",
          "id": "_example__reset",
          "component": () => import('../src/pages/example/_reset.svelte').then(m => m.default)
        },
        {
          "isFile": false,
          "isDir": true,
          "file": "aliasing",
          "filepath": "/example/aliasing",
          "name": "aliasing",
          "ext": "",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing",
          "children": [
            {
              "isFile": true,
              "isDir": false,
              "file": "_layout.svelte",
              "filepath": "/example/aliasing/_layout.svelte",
              "name": "_layout",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/_layout.svelte",
              "importPath": "../src/pages/example/aliasing/_layout.svelte",
              "isLayout": true,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/aliasing",
              "id": "_example_aliasing__layout",
              "component": () => import('../src/pages/example/aliasing/_layout.svelte').then(m => m.default)
            },
            {
              "isFile": true,
              "isDir": false,
              "file": "index.svelte",
              "filepath": "/example/aliasing/index.svelte",
              "name": "index",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/index.svelte",
              "importPath": "../src/pages/example/aliasing/index.svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": true,
              "isFallback": false,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/aliasing/index",
              "id": "_example_aliasing_index",
              "component": () => import('../src/pages/example/aliasing/index.svelte').then(m => m.default)
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "v1",
              "filepath": "/example/aliasing/v1",
              "name": "v1",
              "ext": "",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/v1",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "_layout.svelte",
                  "filepath": "/example/aliasing/v1/_layout.svelte",
                  "name": "_layout",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/v1/_layout.svelte",
                  "importPath": "../src/pages/example/aliasing/v1/_layout.svelte",
                  "isLayout": true,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": false,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/aliasing/v1",
                  "id": "_example_aliasing_v1__layout",
                  "component": () => import('../src/pages/example/aliasing/v1/_layout.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "feature1.svelte",
                  "filepath": "/example/aliasing/v1/feature1.svelte",
                  "name": "feature1",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/v1/feature1.svelte",
                  "importPath": "../src/pages/example/aliasing/v1/feature1.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/aliasing/v1/feature1",
                  "id": "_example_aliasing_v1_feature1",
                  "component": () => import('../src/pages/example/aliasing/v1/feature1.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "feature2.svelte",
                  "filepath": "/example/aliasing/v1/feature2.svelte",
                  "name": "feature2",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/v1/feature2.svelte",
                  "importPath": "../src/pages/example/aliasing/v1/feature2.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/aliasing/v1/feature2",
                  "id": "_example_aliasing_v1_feature2",
                  "component": () => import('../src/pages/example/aliasing/v1/feature2.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "feature3.svelte",
                  "filepath": "/example/aliasing/v1/feature3.svelte",
                  "name": "feature3",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/v1/feature3.svelte",
                  "importPath": "../src/pages/example/aliasing/v1/feature3.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/aliasing/v1/feature3",
                  "id": "_example_aliasing_v1_feature3",
                  "component": () => import('../src/pages/example/aliasing/v1/feature3.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/example/aliasing/v1/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/v1/index.svelte",
                  "importPath": "../src/pages/example/aliasing/v1/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/aliasing/v1/index",
                  "id": "_example_aliasing_v1_index",
                  "component": () => import('../src/pages/example/aliasing/v1/index.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/aliasing/v1"
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "v1.1",
              "filepath": "/example/aliasing/v1.1",
              "name": "v1.1",
              "ext": "",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/v1.1",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "_fallback.svelte",
                  "filepath": "/example/aliasing/v1.1/_fallback.svelte",
                  "name": "_fallback",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/v1.1/_fallback.svelte",
                  "importPath": "../src/pages/example/aliasing/v1.1/_fallback.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": true,
                  "isPage": false,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/aliasing/v1.1/_fallback",
                  "id": "_example_aliasing_v1_1__fallback",
                  "component": () => import('../src/pages/example/aliasing/v1.1/_fallback.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "_layout.svelte",
                  "filepath": "/example/aliasing/v1.1/_layout.svelte",
                  "name": "_layout",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/v1.1/_layout.svelte",
                  "importPath": "../src/pages/example/aliasing/v1.1/_layout.svelte",
                  "isLayout": true,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": false,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/aliasing/v1.1",
                  "id": "_example_aliasing_v1_1__layout",
                  "component": () => import('../src/pages/example/aliasing/v1.1/_layout.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "feature2.svelte",
                  "filepath": "/example/aliasing/v1.1/feature2.svelte",
                  "name": "feature2",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/v1.1/feature2.svelte",
                  "importPath": "../src/pages/example/aliasing/v1.1/feature2.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/aliasing/v1.1/feature2",
                  "id": "_example_aliasing_v1_1_feature2",
                  "component": () => import('../src/pages/example/aliasing/v1.1/feature2.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/example/aliasing/v1.1/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/aliasing/v1.1/index.svelte",
                  "importPath": "../src/pages/example/aliasing/v1.1/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/aliasing/v1.1/index",
                  "id": "_example_aliasing_v1_1_index",
                  "component": () => import('../src/pages/example/aliasing/v1.1/index.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/aliasing/v1.1"
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example/aliasing"
        },
        {
          "isFile": false,
          "isDir": true,
          "file": "api",
          "filepath": "/example/api",
          "name": "api",
          "ext": "",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/api",
          "children": [
            {
              "isFile": true,
              "isDir": false,
              "file": "_layout.svelte",
              "filepath": "/example/api/_layout.svelte",
              "name": "_layout",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/api/_layout.svelte",
              "importPath": "../src/pages/example/api/_layout.svelte",
              "isLayout": true,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/api",
              "id": "_example_api__layout",
              "component": () => import('../src/pages/example/api/_layout.svelte').then(m => m.default)
            },
            {
              "isFile": true,
              "isDir": false,
              "file": "[showId].svelte",
              "filepath": "/example/api/[showId].svelte",
              "name": "[showId]",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/api/[showId].svelte",
              "importPath": "../src/pages/example/api/[showId].svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/api/:showId",
              "id": "_example_api__showId",
              "component": () => import('../src/pages/example/api/[showId].svelte').then(m => m.default)
            },
            {
              "isFile": true,
              "isDir": false,
              "file": "index.svelte",
              "filepath": "/example/api/index.svelte",
              "name": "index",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/api/index.svelte",
              "importPath": "../src/pages/example/api/index.svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": true,
              "isFallback": false,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/api/index",
              "id": "_example_api_index",
              "component": () => import('../src/pages/example/api/index.svelte').then(m => m.default)
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example/api"
        },
        {
          "isFile": false,
          "isDir": true,
          "file": "app",
          "filepath": "/example/app",
          "name": "app",
          "ext": "",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/app",
          "children": [
            {
              "isFile": true,
              "isDir": false,
              "file": "_fallback.svelte",
              "filepath": "/example/app/_fallback.svelte",
              "name": "_fallback",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/app/_fallback.svelte",
              "importPath": "../src/pages/example/app/_fallback.svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": true,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/app/_fallback",
              "id": "_example_app__fallback",
              "component": () => import('../src/pages/example/app/_fallback.svelte').then(m => m.default)
            },
            {
              "isFile": true,
              "isDir": false,
              "file": "_reset.svelte",
              "filepath": "/example/app/_reset.svelte",
              "name": "_reset",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/app/_reset.svelte",
              "importPath": "../src/pages/example/app/_reset.svelte",
              "isLayout": true,
              "isReset": true,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/app",
              "id": "_example_app__reset",
              "component": () => import('../src/pages/example/app/_reset.svelte').then(m => m.default)
            },
            {
              "isFile": true,
              "isDir": false,
              "file": "index.svelte",
              "filepath": "/example/app/index.svelte",
              "name": "index",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/app/index.svelte",
              "importPath": "../src/pages/example/app/index.svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": true,
              "isFallback": false,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/app/index",
              "id": "_example_app_index",
              "component": () => import('../src/pages/example/app/index.svelte').then(m => m.default)
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "login",
              "filepath": "/example/app/login",
              "name": "login",
              "ext": "",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/app/login",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "_reset.svelte",
                  "filepath": "/example/app/login/_reset.svelte",
                  "name": "_reset",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/app/login/_reset.svelte",
                  "importPath": "../src/pages/example/app/login/_reset.svelte",
                  "isLayout": true,
                  "isReset": true,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": false,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/app/login",
                  "id": "_example_app_login__reset",
                  "component": () => import('../src/pages/example/app/login/_reset.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/example/app/login/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/app/login/index.svelte",
                  "importPath": "../src/pages/example/app/login/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/app/login/index",
                  "id": "_example_app_login_index",
                  "component": () => import('../src/pages/example/app/login/index.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/app/login"
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example/app"
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "index.svelte",
          "filepath": "/example/index.svelte",
          "name": "index",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/index.svelte",
          "importPath": "../src/pages/example/index.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": true,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example/index",
          "id": "_example_index",
          "component": () => import('../src/pages/example/index.svelte').then(m => m.default)
        },
        {
          "isFile": false,
          "isDir": true,
          "file": "layouts",
          "filepath": "/example/layouts",
          "name": "layouts",
          "ext": "",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/layouts",
          "children": [
            {
              "isFile": true,
              "isDir": false,
              "file": "_layout.svelte",
              "filepath": "/example/layouts/_layout.svelte",
              "name": "_layout",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/layouts/_layout.svelte",
              "importPath": "../src/pages/example/layouts/_layout.svelte",
              "isLayout": true,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/layouts",
              "id": "_example_layouts__layout",
              "component": () => import('../src/pages/example/layouts/_layout.svelte').then(m => m.default)
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "child",
              "filepath": "/example/layouts/child",
              "name": "child",
              "ext": "",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/layouts/child",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "_layout.svelte",
                  "filepath": "/example/layouts/child/_layout.svelte",
                  "name": "_layout",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/layouts/child/_layout.svelte",
                  "importPath": "../src/pages/example/layouts/child/_layout.svelte",
                  "isLayout": true,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": false,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/layouts/child",
                  "id": "_example_layouts_child__layout",
                  "component": () => import('../src/pages/example/layouts/child/_layout.svelte').then(m => m.default)
                },
                {
                  "isFile": false,
                  "isDir": true,
                  "file": "grandchild",
                  "filepath": "/example/layouts/child/grandchild",
                  "name": "grandchild",
                  "ext": "",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/layouts/child/grandchild",
                  "children": [
                    {
                      "isFile": true,
                      "isDir": false,
                      "file": "_layout.svelte",
                      "filepath": "/example/layouts/child/grandchild/_layout.svelte",
                      "name": "_layout",
                      "ext": "svelte",
                      "badExt": false,
                      "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/layouts/child/grandchild/_layout.svelte",
                      "importPath": "../src/pages/example/layouts/child/grandchild/_layout.svelte",
                      "isLayout": true,
                      "isReset": false,
                      "isIndex": false,
                      "isFallback": false,
                      "isPage": false,
                      "ownMeta": {},
                      "meta": {
                        "preload": false,
                        "prerender": true,
                        "precache-order": false,
                        "precache-proximity": true,
                        "recursive": true
                      },
                      "path": "/example/layouts/child/grandchild",
                      "id": "_example_layouts_child_grandchild__layout",
                      "component": () => import('../src/pages/example/layouts/child/grandchild/_layout.svelte').then(m => m.default)
                    },
                    {
                      "isFile": true,
                      "isDir": false,
                      "file": "index.svelte",
                      "filepath": "/example/layouts/child/grandchild/index.svelte",
                      "name": "index",
                      "ext": "svelte",
                      "badExt": false,
                      "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/layouts/child/grandchild/index.svelte",
                      "importPath": "../src/pages/example/layouts/child/grandchild/index.svelte",
                      "isLayout": false,
                      "isReset": false,
                      "isIndex": true,
                      "isFallback": false,
                      "isPage": true,
                      "ownMeta": {},
                      "meta": {
                        "preload": false,
                        "prerender": true,
                        "precache-order": false,
                        "precache-proximity": true,
                        "recursive": true
                      },
                      "path": "/example/layouts/child/grandchild/index",
                      "id": "_example_layouts_child_grandchild_index",
                      "component": () => import('../src/pages/example/layouts/child/grandchild/index.svelte').then(m => m.default)
                    }
                  ],
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": false,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/layouts/child/grandchild"
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/example/layouts/child/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/layouts/child/index.svelte",
                  "importPath": "../src/pages/example/layouts/child/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/layouts/child/index",
                  "id": "_example_layouts_child_index",
                  "component": () => import('../src/pages/example/layouts/child/index.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/layouts/child"
            },
            {
              "isFile": true,
              "isDir": false,
              "file": "index.svelte",
              "filepath": "/example/layouts/index.svelte",
              "name": "index",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/layouts/index.svelte",
              "importPath": "../src/pages/example/layouts/index.svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": true,
              "isFallback": false,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/layouts/index",
              "id": "_example_layouts_index",
              "component": () => import('../src/pages/example/layouts/index.svelte').then(m => m.default)
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example/layouts"
        },
        {
          "isFile": false,
          "isDir": true,
          "file": "modal",
          "filepath": "/example/modal",
          "name": "modal",
          "ext": "",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/modal",
          "children": [
            {
              "isFile": true,
              "isDir": false,
              "file": "_layout.svelte",
              "filepath": "/example/modal/_layout.svelte",
              "name": "_layout",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/modal/_layout.svelte",
              "importPath": "../src/pages/example/modal/_layout.svelte",
              "isLayout": true,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/modal",
              "id": "_example_modal__layout",
              "component": () => import('../src/pages/example/modal/_layout.svelte').then(m => m.default)
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "animated",
              "filepath": "/example/modal/animated",
              "name": "animated",
              "ext": "",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/modal/animated",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "_layout.svelte",
                  "filepath": "/example/modal/animated/_layout.svelte",
                  "name": "_layout",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/modal/animated/_layout.svelte",
                  "importPath": "../src/pages/example/modal/animated/_layout.svelte",
                  "isLayout": true,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": false,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/modal/animated",
                  "id": "_example_modal_animated__layout",
                  "component": () => import('../src/pages/example/modal/animated/_layout.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "[key].svelte",
                  "filepath": "/example/modal/animated/[key].svelte",
                  "name": "[key]",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/modal/animated/[key].svelte",
                  "importPath": "../src/pages/example/modal/animated/[key].svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/modal/animated/:key",
                  "id": "_example_modal_animated__key",
                  "component": () => import('../src/pages/example/modal/animated/[key].svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/example/modal/animated/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/modal/animated/index.svelte",
                  "importPath": "../src/pages/example/modal/animated/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/modal/animated/index",
                  "id": "_example_modal_animated_index",
                  "component": () => import('../src/pages/example/modal/animated/index.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/modal/animated"
            },
            {
              "isFile": false,
              "isDir": true,
              "file": "basic",
              "filepath": "/example/modal/basic",
              "name": "basic",
              "ext": "",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/modal/basic",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "_layout.svelte",
                  "filepath": "/example/modal/basic/_layout.svelte",
                  "name": "_layout",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/modal/basic/_layout.svelte",
                  "importPath": "../src/pages/example/modal/basic/_layout.svelte",
                  "isLayout": true,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": false,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/modal/basic",
                  "id": "_example_modal_basic__layout",
                  "component": () => import('../src/pages/example/modal/basic/_layout.svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "[key].svelte",
                  "filepath": "/example/modal/basic/[key].svelte",
                  "name": "[key]",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/modal/basic/[key].svelte",
                  "importPath": "../src/pages/example/modal/basic/[key].svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/modal/basic/:key",
                  "id": "_example_modal_basic__key",
                  "component": () => import('../src/pages/example/modal/basic/[key].svelte').then(m => m.default)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/example/modal/basic/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/modal/basic/index.svelte",
                  "importPath": "../src/pages/example/modal/basic/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true
                  },
                  "path": "/example/modal/basic/index",
                  "id": "_example_modal_basic_index",
                  "component": () => import('../src/pages/example/modal/basic/index.svelte').then(m => m.default)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/modal/basic"
            },
            {
              "isFile": true,
              "isDir": false,
              "file": "index.svelte",
              "filepath": "/example/modal/index.svelte",
              "name": "index",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/modal/index.svelte",
              "importPath": "../src/pages/example/modal/index.svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": true,
              "isFallback": false,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/modal/index",
              "id": "_example_modal_index",
              "component": () => import('../src/pages/example/modal/index.svelte').then(m => m.default)
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example/modal"
        },
        {
          "isFile": false,
          "isDir": true,
          "file": "reset",
          "filepath": "/example/reset",
          "name": "reset",
          "ext": "",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/reset",
          "children": [
            {
              "isFile": true,
              "isDir": false,
              "file": "_fallback.svelte",
              "filepath": "/example/reset/_fallback.svelte",
              "name": "_fallback",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/reset/_fallback.svelte",
              "importPath": "../src/pages/example/reset/_fallback.svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": true,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/reset/_fallback",
              "id": "_example_reset__fallback",
              "component": () => import('../src/pages/example/reset/_fallback.svelte').then(m => m.default)
            },
            {
              "isFile": true,
              "isDir": false,
              "file": "_reset.svelte",
              "filepath": "/example/reset/_reset.svelte",
              "name": "_reset",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/reset/_reset.svelte",
              "importPath": "../src/pages/example/reset/_reset.svelte",
              "isLayout": true,
              "isReset": true,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/reset",
              "id": "_example_reset__reset",
              "component": () => import('../src/pages/example/reset/_reset.svelte').then(m => m.default)
            },
            {
              "isFile": true,
              "isDir": false,
              "file": "index.svelte",
              "filepath": "/example/reset/index.svelte",
              "name": "index",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/reset/index.svelte",
              "importPath": "../src/pages/example/reset/index.svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": true,
              "isFallback": false,
              "isPage": true,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/reset/index",
              "id": "_example_reset_index",
              "component": () => import('../src/pages/example/reset/index.svelte').then(m => m.default)
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example/reset"
        },
        {
          "isFile": true,
          "isDir": false,
          "file": "Splash.svelte",
          "filepath": "/example/Splash.svelte",
          "name": "Splash",
          "ext": "svelte",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/Splash.svelte",
          "importPath": "../src/pages/example/Splash.svelte",
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": true,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example/Splash",
          "id": "_example_Splash",
          "component": () => import('../src/pages/example/Splash.svelte').then(m => m.default)
        },
        {
          "isFile": false,
          "isDir": true,
          "file": "transitions",
          "filepath": "/example/transitions",
          "name": "transitions",
          "ext": "",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions",
          "children": [
            {
              "isFile": false,
              "isDir": true,
              "file": "tabs",
              "filepath": "/example/transitions/tabs",
              "name": "tabs",
              "ext": "",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions/tabs",
              "children": [
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "_reset.svelte",
                  "filepath": "/example/transitions/tabs/_reset.svelte",
                  "name": "_reset",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions/tabs/_reset.svelte",
                  "importPath": "../src/pages/example/transitions/tabs/_reset.svelte",
                  "isLayout": true,
                  "isReset": true,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": false,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true,
                    "$$bundleId": "_example_transitions_tabs.js"
                  },
                  "path": "/example/transitions/tabs",
                  "id": "_example_transitions_tabs__reset",
                  "component": () => import('./_example_transitions_tabs.js').then(m => m._example_transitions_tabs__reset)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "home.svelte",
                  "filepath": "/example/transitions/tabs/home.svelte",
                  "name": "home",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions/tabs/home.svelte",
                  "importPath": "../src/pages/example/transitions/tabs/home.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {
                    "index": 0
                  },
                  "meta": {
                    "index": 0,
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true,
                    "$$bundleId": "_example_transitions_tabs.js"
                  },
                  "path": "/example/transitions/tabs/home",
                  "id": "_example_transitions_tabs_home",
                  "component": () => import('./_example_transitions_tabs.js').then(m => m._example_transitions_tabs_home)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "index.svelte",
                  "filepath": "/example/transitions/tabs/index.svelte",
                  "name": "index",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions/tabs/index.svelte",
                  "importPath": "../src/pages/example/transitions/tabs/index.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": true,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {},
                  "meta": {
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true,
                    "$$bundleId": "_example_transitions_tabs.js"
                  },
                  "path": "/example/transitions/tabs/index",
                  "id": "_example_transitions_tabs_index",
                  "component": () => import('./_example_transitions_tabs.js').then(m => m._example_transitions_tabs_index)
                },
                {
                  "isFile": false,
                  "isDir": true,
                  "file": "feed",
                  "filepath": "/example/transitions/tabs/feed",
                  "name": "feed",
                  "ext": "",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions/tabs/feed",
                  "children": [
                    {
                      "isFile": true,
                      "isDir": false,
                      "file": "_layout.svelte",
                      "filepath": "/example/transitions/tabs/feed/_layout.svelte",
                      "name": "_layout",
                      "ext": "svelte",
                      "badExt": false,
                      "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions/tabs/feed/_layout.svelte",
                      "importPath": "../src/pages/example/transitions/tabs/feed/_layout.svelte",
                      "isLayout": true,
                      "isReset": false,
                      "isIndex": false,
                      "isFallback": false,
                      "isPage": false,
                      "ownMeta": {},
                      "meta": {
                        "preload": false,
                        "prerender": true,
                        "precache-order": false,
                        "precache-proximity": true,
                        "recursive": true,
                        "$$bundleId": "_example_transitions_tabs.js"
                      },
                      "path": "/example/transitions/tabs/feed",
                      "id": "_example_transitions_tabs_feed__layout",
                      "component": () => import('./_example_transitions_tabs.js').then(m => m._example_transitions_tabs_feed__layout)
                    },
                    {
                      "isFile": false,
                      "isDir": true,
                      "file": "[id]",
                      "filepath": "/example/transitions/tabs/feed/[id]",
                      "name": "[id]",
                      "ext": "",
                      "badExt": false,
                      "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions/tabs/feed/[id]",
                      "children": [
                        {
                          "isFile": true,
                          "isDir": false,
                          "file": "index.svelte",
                          "filepath": "/example/transitions/tabs/feed/[id]/index.svelte",
                          "name": "index",
                          "ext": "svelte",
                          "badExt": false,
                          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions/tabs/feed/[id]/index.svelte",
                          "importPath": "../src/pages/example/transitions/tabs/feed/[id]/index.svelte",
                          "isLayout": false,
                          "isReset": false,
                          "isIndex": true,
                          "isFallback": false,
                          "isPage": true,
                          "ownMeta": {},
                          "meta": {
                            "preload": false,
                            "prerender": true,
                            "precache-order": false,
                            "precache-proximity": true,
                            "recursive": true,
                            "$$bundleId": "_example_transitions_tabs.js"
                          },
                          "path": "/example/transitions/tabs/feed/:id/index",
                          "id": "_example_transitions_tabs_feed__id_index",
                          "component": () => import('./_example_transitions_tabs.js').then(m => m._example_transitions_tabs_feed__id_index)
                        }
                      ],
                      "isLayout": false,
                      "isReset": false,
                      "isIndex": false,
                      "isFallback": false,
                      "isPage": false,
                      "ownMeta": {},
                      "meta": {
                        "preload": false,
                        "prerender": true,
                        "precache-order": false,
                        "precache-proximity": true,
                        "recursive": true,
                        "$$bundleId": "_example_transitions_tabs.js"
                      },
                      "path": "/example/transitions/tabs/feed/:id"
                    },
                    {
                      "isFile": true,
                      "isDir": false,
                      "file": "index.svelte",
                      "filepath": "/example/transitions/tabs/feed/index.svelte",
                      "name": "index",
                      "ext": "svelte",
                      "badExt": false,
                      "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions/tabs/feed/index.svelte",
                      "importPath": "../src/pages/example/transitions/tabs/feed/index.svelte",
                      "isLayout": false,
                      "isReset": false,
                      "isIndex": true,
                      "isFallback": false,
                      "isPage": true,
                      "ownMeta": {},
                      "meta": {
                        "preload": false,
                        "prerender": true,
                        "precache-order": false,
                        "precache-proximity": true,
                        "recursive": true,
                        "$$bundleId": "_example_transitions_tabs.js"
                      },
                      "path": "/example/transitions/tabs/feed/index",
                      "id": "_example_transitions_tabs_feed_index",
                      "component": () => import('./_example_transitions_tabs.js').then(m => m._example_transitions_tabs_feed_index)
                    }
                  ],
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": false,
                  "ownMeta": {
                    "index": 1
                  },
                  "meta": {
                    "index": 1,
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true,
                    "$$bundleId": "_example_transitions_tabs.js"
                  },
                  "path": "/example/transitions/tabs/feed"
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "updates.svelte",
                  "filepath": "/example/transitions/tabs/updates.svelte",
                  "name": "updates",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions/tabs/updates.svelte",
                  "importPath": "../src/pages/example/transitions/tabs/updates.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {
                    "index": 2
                  },
                  "meta": {
                    "index": 2,
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true,
                    "$$bundleId": "_example_transitions_tabs.js"
                  },
                  "path": "/example/transitions/tabs/updates",
                  "id": "_example_transitions_tabs_updates",
                  "component": () => import('./_example_transitions_tabs.js').then(m => m._example_transitions_tabs_updates)
                },
                {
                  "isFile": true,
                  "isDir": false,
                  "file": "settings.svelte",
                  "filepath": "/example/transitions/tabs/settings.svelte",
                  "name": "settings",
                  "ext": "svelte",
                  "badExt": false,
                  "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/transitions/tabs/settings.svelte",
                  "importPath": "../src/pages/example/transitions/tabs/settings.svelte",
                  "isLayout": false,
                  "isReset": false,
                  "isIndex": false,
                  "isFallback": false,
                  "isPage": true,
                  "ownMeta": {
                    "index": 3
                  },
                  "meta": {
                    "index": 3,
                    "preload": false,
                    "prerender": true,
                    "precache-order": false,
                    "precache-proximity": true,
                    "recursive": true,
                    "$$bundleId": "_example_transitions_tabs.js"
                  },
                  "path": "/example/transitions/tabs/settings",
                  "id": "_example_transitions_tabs_settings",
                  "component": () => import('./_example_transitions_tabs.js').then(m => m._example_transitions_tabs_settings)
                }
              ],
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": false,
              "isPage": false,
              "ownMeta": {
                "bundle": true
              },
              "meta": {
                "bundle": true,
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true,
                "$$bundleId": "_example_transitions_tabs.js"
              },
              "path": "/example/transitions/tabs"
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example/transitions"
        },
        {
          "isFile": false,
          "isDir": true,
          "file": "widget",
          "filepath": "/example/widget",
          "name": "widget",
          "ext": "",
          "badExt": false,
          "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/widget",
          "children": [
            {
              "isFile": true,
              "isDir": false,
              "file": "_fallback.svelte",
              "filepath": "/example/widget/_fallback.svelte",
              "name": "_fallback",
              "ext": "svelte",
              "badExt": false,
              "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/example/widget/_fallback.svelte",
              "importPath": "../src/pages/example/widget/_fallback.svelte",
              "isLayout": false,
              "isReset": false,
              "isIndex": false,
              "isFallback": true,
              "isPage": false,
              "ownMeta": {},
              "meta": {
                "preload": false,
                "prerender": true,
                "precache-order": false,
                "precache-proximity": true,
                "recursive": true
              },
              "path": "/example/widget/_fallback",
              "id": "_example_widget__fallback",
              "component": () => import('../src/pages/example/widget/_fallback.svelte').then(m => m.default)
            }
          ],
          "isLayout": false,
          "isReset": false,
          "isIndex": false,
          "isFallback": false,
          "isPage": false,
          "ownMeta": {},
          "meta": {
            "preload": false,
            "prerender": true,
            "precache-order": false,
            "precache-proximity": true,
            "recursive": true
          },
          "path": "/example/widget"
        }
      ],
      "isLayout": false,
      "isReset": false,
      "isIndex": false,
      "isFallback": false,
      "isPage": false,
      "ownMeta": {},
      "meta": {
        "preload": false,
        "prerender": true,
        "precache-order": false,
        "precache-proximity": true,
        "recursive": true
      },
      "path": "/example"
    },
    {
      "isFile": true,
      "isDir": false,
      "file": "index.svelte",
      "filepath": "/index.svelte",
      "name": "index",
      "ext": "svelte",
      "badExt": false,
      "absolutePath": "/Users/bag-yeong-ung/Documents/projects/svelte-routify/src/pages/index.svelte",
      "importPath": "../src/pages/index.svelte",
      "isLayout": false,
      "isReset": false,
      "isIndex": true,
      "isFallback": false,
      "isPage": true,
      "ownMeta": {},
      "meta": {
        "preload": false,
        "prerender": true,
        "precache-order": false,
        "precache-proximity": true,
        "recursive": true
      },
      "path": "/index",
      "id": "_index",
      "component": () => import('../src/pages/index.svelte').then(m => m.default)
    }
  ],
  "isLayout": false,
  "isReset": false,
  "isIndex": false,
  "isFallback": false,
  "meta": {
    "preload": false,
    "prerender": true,
    "precache-order": false,
    "precache-proximity": true,
    "recursive": true
  },
  "path": "/"
}


export const {tree, routes} = buildClientTree(_tree)

